/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boluketan_projectdisprog;

import java.util.ArrayList;
import java.util.List;
import java.sql.Timestamp;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class SystemReservasi extends javax.swing.JFrame {

    /**
     * Creates new form SystemReservasi
     */
    public SystemReservasi() {
        initComponents();
        loadDataReservasi();
    }
    
    private List<Integer> daftarIdMeja = new ArrayList<>();
    private int idMejaSaatIni = 0;
    
    private void tampilkanMejaTersedia(List<boluketan_projectdisprog.Meja> mejaTersedia) {
        cmbPilihMeja.removeAllItems();
        daftarIdMeja.clear();

        if (mejaTersedia.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada meja kosong untuk kriteria ini.");
            return;
        }

        for (boluketan_projectdisprog.Meja m : mejaTersedia) {
            cmbPilihMeja.addItem("Meja " + m.getIdMeja() + " (kapasitas " + m.getJumlahKonsumen() + ")");
            daftarIdMeja.add(m.getIdMeja());
        }
    }
    
    private void loadDataReservasi() {
    List<boluketan_projectdisprog.Reservasi> daftarReservasi = lihatReservasi();

    DefaultTableModel model = (DefaultTableModel) tableReservasi.getModel();
    model.setRowCount(0); // kosongkan dulu isi tabel

    for (boluketan_projectdisprog.Reservasi r : daftarReservasi) {
        model.addRow(new Object[]{
            r.getIdreservasi(),
            r.getTanggalReservasi(),
            r.getJumlahTamu(),
            r.getStatusReservasi(),
            r.getUserIduser(),
            r.getMejaIdmeja(),
            r.getJamReservasi(),
            r.getTotalHarga()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDReservasi = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        txtJumlahTamu = new javax.swing.JTextField();
        cmbPilihMeja = new javax.swing.JComboBox<>();
        btnCekKetersediaan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservasi = new javax.swing.JTable();
        btnReservasi = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Reservasi");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Jam");

        jLabel4.setText("Status");

        jLabel5.setText("Jumlah Tamu");

        jLabel6.setText("Pilih Meja");

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        txtJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamActionPerformed(evt);
            }
        });

        txtJumlahTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahTamuActionPerformed(evt);
            }
        });

        cmbPilihMeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihMejaActionPerformed(evt);
            }
        });

        btnCekKetersediaan.setText("Cek Ketersediaan");
        btnCekKetersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekKetersediaanActionPerformed(evt);
            }
        });

        tableReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Tamu", "Status", "ID User", "Meja", "Jam", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReservasi);

        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Complete", "Cancel", " " }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReservasi)
                        .addGap(57, 57, 57)
                        .addComponent(btnUpdate)
                        .addGap(56, 56, 56)
                        .addComponent(btnCancel))
                    .addComponent(btnCekKetersediaan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIDReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtJam))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtJumlahTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPilihMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJumlahTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbPilihMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnCekKetersediaan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservasi)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void txtJumlahTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahTamuActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        
        int idMeja;
        if (daftarIdMeja.isEmpty() || cmbPilihMeja.getSelectedIndex() < 0) {
            idMeja = idMejaSaatIni;
        } else {
            idMeja = daftarIdMeja.get(cmbPilihMeja.getSelectedIndex());
        }
        String tanggal = txtTanggal.getText().trim();
        String jam = txtJam.getText().trim();
        int jumlahTamu = Integer.parseInt(txtJumlahTamu.getText().trim());
        String status = (String) cmbStatus.getSelectedItem();
        int idUser = 1; // TODO: ganti dengan id user yang sedang login

        String tanggalReservasi = tanggal + " 00:00:00";
        String jamReservasi = tanggal + " " + jam + ":00";

        String hasil = updateReservasi(tanggalReservasi, jumlahTamu, status, idUser, idMeja, jamReservasi);
        JOptionPane.showMessageDialog(this, hasil);
        loadDataReservasi();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        int idReservasi = Integer.parseInt(txtIDReservasi.getText().trim());
        String hasil = batalkanReservasi(idReservasi);
        JOptionPane.showMessageDialog(this, hasil);
        loadDataReservasi();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnCekKetersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekKetersediaanActionPerformed
        
        String tanggal = txtTanggal.getText().trim();
        String jam = txtJam.getText().trim();
        int jumlahTamu = Integer.parseInt(txtJumlahTamu.getText().trim());
        String jamReservasi = tanggal + " " + jam + ":00";

        List<boluketan_projectdisprog.Meja> mejaTersedia = cariMejaTersedia(jamReservasi, jumlahTamu);
        tampilkanMejaTersedia(mejaTersedia);

    }//GEN-LAST:event_btnCekKetersediaanActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        
        int idMeja = daftarIdMeja.get(cmbPilihMeja.getSelectedIndex());
        String tanggal = txtTanggal.getText().trim();
        String jam = txtJam.getText().trim();
        int jumlahTamu = Integer.parseInt(txtJumlahTamu.getText().trim());
        String status = "Pending"; // dipaksa, tidak ambil dari cmbStatus
        int idUser = 1; // TODO: ganti dengan id user yang sedang login

        String tanggalReservasi = tanggal + " 00:00:00";
        String jamReservasi = tanggal + " " + jam + ":00";

        String hasil = tambahReservasi(tanggalReservasi, jumlahTamu, status, idUser, idMeja, jamReservasi, 0);
        JOptionPane.showMessageDialog(this, hasil);
        loadDataReservasi();
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void cmbPilihMejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihMejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPilihMejaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCekKetersediaan;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbPilihMeja;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReservasi;
    private javax.swing.JTextField txtIDReservasi;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtJumlahTamu;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

    private static String batalkanReservasi(int arg0) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.batalkanReservasi(arg0);
    }

    private static java.util.List<boluketan_projectdisprog.Meja> cariMejaTersedia(java.lang.String arg0, int arg1) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.cariMejaTersedia(arg0, arg1);
    }

    


    private static String updateReservasi(java.lang.String arg0, int arg1, java.lang.String arg2, int arg3, int arg4, java.lang.String arg5) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.updateReservasi(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    private static java.util.List<boluketan_projectdisprog.Reservasi> lihatReservasi() {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.lihatReservasi();
    }

    private static String tambahReservasi(String arg0, int arg1, String arg2, int arg3, int arg4, String arg5, double arg6) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.tambahReservasi(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    }   
}
