/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boluketan_projectdisprog;

import java.util.ArrayList;
import java.util.List;
import java.sql.Timestamp;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class SystemReservasi extends javax.swing.JFrame {

    /**
     * Creates new form SystemReservasi
     */
    User orang = new User();
    public SystemReservasi(User user1) {
        this.orang = user1;
        initComponents();
        setupSpinner();
        loadDataReservasi();
    }
    
    private List<Integer> daftarIdMeja = new ArrayList<>();
    private int idMejaSaatIni = 0;
    
    private void setupSpinner() {
        spinnerTanggal.setModel(new javax.swing.SpinnerDateModel());
        spinnerTanggal.setEditor(new javax.swing.JSpinner.DateEditor(spinnerTanggal, "yyyy-MM-dd"));

        spinnerJam.setModel(new javax.swing.SpinnerDateModel());
        spinnerJam.setEditor(new javax.swing.JSpinner.DateEditor(spinnerJam, "HH:mm"));
    }

    
    private void loadDataReservasi() {
    List<boluketan_projectdisprog.Reservasi> daftarReservasi = lihatReservasi(orang.getIdUser());

    DefaultTableModel model = (DefaultTableModel) tableReservasi.getModel();
    model.setRowCount(0); // kosongkan dulu isi tabel

    for (boluketan_projectdisprog.Reservasi r : daftarReservasi) {
        String[]jam = r.getJamReservasi().split(" ");
        model.addRow(new Object[]{
            r.getIdreservasi(),
            r.getTanggalReservasi(),
            r.getJumlahTamu(),
            r.getStatusReservasi(),
            r.getUserIduser(),
            r.getMejaIdmeja(),
            jam[1],
            r.getTotalHarga()
        });
    }
}
    
    private String getTanggalString() {
        java.util.Date tanggal = (java.util.Date) spinnerTanggal.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(tanggal);
    }

    private String getJamString() {
        java.util.Date jam = (java.util.Date) spinnerJam.getValue();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm");
        return sdf.format(jam);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDReservasi = new javax.swing.JTextField();
        txtJumlahTamu = new javax.swing.JTextField();
        btnCekKetersediaan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservasi = new javax.swing.JTable();
        btnReservasi = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        spinnerTanggal = new javax.swing.JSpinner();
        spinnerJam = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Reservasi");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Jam");

        jLabel5.setText("Jumlah Tamu");

        txtIDReservasi.setEnabled(false);

        txtJumlahTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahTamuActionPerformed(evt);
            }
        });

        btnCekKetersediaan.setText("Cek Ketersediaan");
        btnCekKetersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekKetersediaanActionPerformed(evt);
            }
        });

        tableReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Tamu", "Status", "ID User", "Meja", "Jam", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReservasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReservasi);

        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReservasi)
                        .addGap(57, 57, 57)
                        .addComponent(btnUpdate)
                        .addGap(56, 56, 56)
                        .addComponent(btnCancel)
                        .addGap(28, 28, 28)
                        .addComponent(btnReturn))
                    .addComponent(btnCekKetersediaan)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlahTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinnerJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJumlahTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCekKetersediaan)
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservasi)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel)
                    .addComponent(btnReturn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJumlahTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahTamuActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtIDReservasi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data reservasi di tabel terlebih dahulu!");
            return;
        }

        int idReservasi = Integer.parseInt(txtIDReservasi.getText());
        String tanggal = getTanggalString();  
        String jam = getJamString();
        int jumlahTamu = Integer.parseInt(txtJumlahTamu.getText().trim());

        // Gunakan meja saat ini jika combobox kosong
        int idMeja = idMejaSaatIni;

        String status = "Confirmed"; // Status otomatis berubah jadi terkonfirmasi saat diupdate

        String tanggalReservasi = tanggal + " 00:00:00";
        String jamReservasi = tanggal + " " + jam + ":00";

        // Panggil Web Service untuk Update
        String hasil = updateReservasi(tanggalReservasi, jumlahTamu, status, orang.getIdUser(), idMeja, jamReservasi);
        JOptionPane.showMessageDialog(this, hasil);

        loadDataReservasi(); // Refresh tabel
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        if (txtIDReservasi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data reservasi di tabel terlebih dahulu!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin membatalkan reservasi ini?", "Hapus Data", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            int idReservasi = Integer.parseInt(txtIDReservasi.getText());

            // Panggil Web Service untuk Delete/Cancel
            String hasil = batalkanReservasi(idReservasi);
            JOptionPane.showMessageDialog(this, hasil);

            loadDataReservasi(); // Refresh tabel
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCekKetersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekKetersediaanActionPerformed
        
        String tanggal = getTanggalString();
        String jam = getJamString();
        int jumlahTamu = Integer.parseInt(txtJumlahTamu.getText().trim());
        String jamReservasi = tanggal + " " + jam + ":00";

        List<boluketan_projectdisprog.Meja> mejaCocok = cariMejaTersedia(jamReservasi, jumlahTamu);

        if (mejaCocok.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada meja tersedia untuk " + jumlahTamu + " orang pada waktu tersebut.");
        } else {
            JOptionPane.showMessageDialog(this, mejaCocok.size() + " meja tersedia untuk waktu tersebut.");
        }


    }//GEN-LAST:event_btnCekKetersediaanActionPerformed

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        
        // 1. Validasi dasar: pastikan input teks tidak kosong
        if (txtJumlahTamu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah Tamu wajib diisi!");
            return;
        }

        try {
            String tanggal = getTanggalString();  
            String jam = getJamString(); 
            int jumlahTamu = Integer.parseInt(txtJumlahTamu.getText().trim());

            // Format waktu standar SQL
            String jamReservasi = tanggal + " " + jam + ":00";
            String tanggalReservasi = tanggal + " 00:00:00";
            double totalHarga = 0;

            // cari meja
            List<boluketan_projectdisprog.Meja> mejaCocok = cariMejaTersedia(jamReservasi, jumlahTamu);

            // Jika tidak ada meja yang muat/tersedia
            if (mejaCocok.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Maaf, tidak ada meja yang tersedia untuk " + jumlahTamu + " orang pada waktu tersebut.");
                return;
            }

            // Ambil ID meja pertama yang paling pas dari hasil pencarian
            int idMejaDipilih = mejaCocok.get(0).getIdMeja();

            // 3. Panggil Web Service untuk INSERT data reservasi menggunakan meja yang didapat
            int idHasil = tambahReservasi(tanggalReservasi, jumlahTamu, "Pending", orang.getIdUser(), idMejaDipilih, jamReservasi, totalHarga);

            if (idHasil > 0) {
                JOptionPane.showMessageDialog(this, "Reservasi Berhasil di Meja " + idMejaDipilih + "! Melanjutkan ke Pemesanan Makanan...");

                FoodOrdering foodForm = new FoodOrdering(idHasil);
                foodForm.setVisible(true);

                // Sembunyikan form reservasi utama
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal melakukan reservasi.");
            }

            loadDataReservasi(); // Refresh data tabel belakang

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah tamu harus berupa angka!", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void tableReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReservasiMouseClicked
        // TODO add your handling code here:
        int row = tableReservasi.getSelectedRow();
        if (row != -1) {
            // 1. Ambil ID Reservasi dan masukkan ke txtIDReservasi
            String id = String.valueOf(tableReservasi.getValueAt(row, 0));
            txtIDReservasi.setText(id);
                
            // 2. Ambil data Tanggal & Jam
            // Karena format dari database biasanya YYYY-MM-DD HH:MM:SS, kita bersihkan sedikit
            String fullTanggal = String.valueOf(tableReservasi.getValueAt(row, 1));
            String fullJam = String.valueOf(tableReservasi.getValueAt(row, 6));
            String jam;
            if(fullJam.length()>= 5)
            {
                jam = fullJam.substring(0,5);
            }
            else
            {
                jam = fullJam;
            }
            try{
                java.text.SimpleDateFormat sdfTanggal = new java.text.SimpleDateFormat("yyyy-MM-dd");
                java.text.SimpleDateFormat sdfJam = new java.text.SimpleDateFormat("HH:mm");
            
                String tanggalStr;
                if (fullTanggal.length() >= 10) {
                    tanggalStr = fullTanggal.substring(0, 10);
                } else {
                    tanggalStr = fullTanggal;
                }
                
                spinnerTanggal.setValue(sdfTanggal.parse(tanggalStr));
                spinnerJam.setValue(sdfJam.parse(jam));
            
            }catch (Exception ex) {
                System.out.println("Error parsing tanggal/jam: " + ex.getMessage());
            }
            // 3. Ambil Jumlah Tamu
            String tamu = String.valueOf(tableReservasi.getValueAt(row, 2));
            txtJumlahTamu.setText(tamu);

            // 4. Catat ID Meja saat ini agar jika tidak ganti meja, ID ini tetap dipakai
            idMejaSaatIni = Integer.parseInt(String.valueOf(tableReservasi.getValueAt(row, 5)));
        }
    }//GEN-LAST:event_tableReservasiMouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        Home home = new Home(orang);
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCekKetersediaan;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerJam;
    private javax.swing.JSpinner spinnerTanggal;
    private javax.swing.JTable tableReservasi;
    private javax.swing.JTextField txtIDReservasi;
    private javax.swing.JTextField txtJumlahTamu;
    // End of variables declaration//GEN-END:variables

    private static String batalkanReservasi(int arg0) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.batalkanReservasi(arg0);
    }

    private static java.util.List<boluketan_projectdisprog.Meja> cariMejaTersedia(java.lang.String arg0, int arg1) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.cariMejaTersedia(arg0, arg1);
    }

    


    private static String updateReservasi(java.lang.String arg0, int arg1, java.lang.String arg2, int arg3, int arg4, java.lang.String arg5) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.updateReservasi(arg0, arg1, arg2, arg3, arg4, arg5);
    }


    private static int tambahReservasi(String arg0, int arg1, String arg2, int arg3, int arg4, String arg5, double arg6) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.tambahReservasi(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    }

    private static java.util.List<boluketan_projectdisprog.Reservasi> lihatReservasi(int arg0) {
        boluketan_projectdisprog.ReservasiWSService service = new boluketan_projectdisprog.ReservasiWSService();
        boluketan_projectdisprog.ReservasiWS port = service.getReservasiWSPort();
        return port.lihatReservasi(arg0);
    }
}
