/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boluketan_projectdisprog;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class TableManagement extends javax.swing.JFrame {

    /**
     * Creates new form ReservasiTable
     */
    public TableManagement() {
        initComponents();
        loadDataMeja();
    }
    
    private void loadDataMeja() {
        List<boluketan_projectdisprog.Meja> daftarMeja = lihatMeja();

        DefaultTableModel model = (DefaultTableModel) tableMeja.getModel();
        model.setRowCount(0); // kosongkan dulu isi tabel

        for (boluketan_projectdisprog.Meja m : daftarMeja) {
        model.addRow(new Object[]{
            m.getIdMeja(),
            m.getStatus(),
            m.getJumlahKonsumen(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        btnUpdateAdmin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMeja = new javax.swing.JTable();
        cmbStatus = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtJumlahKonsumen = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnUpdateAdmin.setText("Update");
        btnUpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAdminActionPerformed(evt);
            }
        });

        jLabel5.setText("Status Meja");

        tableMeja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Status", "Jumlah Konsumen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMeja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMejaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMeja);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "reservasi", "kosong", "pakai" }));

        btnTambah.setText("Tambah Meja");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        jLabel2.setText("Jumlah Konsumen");

        jLabel4.setText("Pilih Id");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTambah)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtJumlahKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(436, 436, 436)
                                .addComponent(btnUpdateAdmin)))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnUpdateAdmin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtJumlahKonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnTambah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadDataMeja();        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (txtJumlahKonsumen.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Jumlah Konsumen wajib diisi!");

            return;

        }

        try {

            int noMeja = 0;

            String status = "tersedia";

            int jumlahKonsum = Integer.parseInt(
                    txtJumlahKonsumen.getText().trim()
            );

            String hasil = tambahMeja(noMeja, status, jumlahKonsum);

            JOptionPane.showMessageDialog(this, hasil);

            loadDataMeja();

            txtId.setText("");

            txtJumlahKonsumen.setText("");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAdminActionPerformed
        // Validasi: Pastikan ID sudah terisi (dipilih dari tabel)
        if (txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih baris data pada tabel terlebih dahulu!");
            return;
        }

        try {
            int id = Integer.parseInt(txtId.getText().trim());
            String status = cmbStatus.getSelectedItem().toString();
            int jumlahKonsumenUpdate = Integer.parseInt(txtJumlahKonsumen.getText().trim());

            String hasil = updateStatus(id, status, jumlahKonsumenUpdate);
            JOptionPane.showMessageDialog(this, hasil);

            loadDataMeja(); // Refresh tabel

            // Reset inputan
            txtId.setText("");
            txtJumlahKonsumen.setText("");
            cmbStatus.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah konsumen harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateAdminActionPerformed

    private void tableMejaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMejaMouseClicked
        // TODO add your handling code here:
        int row = tableMeja.getSelectedRow();
        if (row != -1) {
            // Isi txtId dari kolom ke-0
            txtId.setText(tableMeja.getValueAt(row, 0).toString());

            // Isi cmbStatus dari kolom ke-1
            String status = tableMeja.getValueAt(row, 1).toString();
            cmbStatus.setSelectedItem(status);

            // Isi txtJumlahKonsumen dari kolom ke-2
            txtJumlahKonsumen.setText(tableMeja.getValueAt(row, 2).toString());
        }
    }//GEN-LAST:event_tableMejaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdateAdmin;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMeja;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlahKonsumen;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<boluketan_projectdisprog.Meja> lihatMeja() {
        boluketan_projectdisprog.MejaWSService service = new boluketan_projectdisprog.MejaWSService();
        boluketan_projectdisprog.MejaWS port = service.getMejaWSPort();
        return port.lihatMeja();
    }

    private static String tambahMeja(int arg0, java.lang.String arg1, int arg2) {
        boluketan_projectdisprog.MejaWSService service = new boluketan_projectdisprog.MejaWSService();
        boluketan_projectdisprog.MejaWS port = service.getMejaWSPort();
        return port.tambahMeja(arg0, arg1, arg2);
    }

    private static String updateStatus(int arg0, java.lang.String arg1, int arg2) {
        boluketan_projectdisprog.MejaWSService service = new boluketan_projectdisprog.MejaWSService();
        boluketan_projectdisprog.MejaWS port = service.getMejaWSPort();
        return port.updateStatus(arg0, arg1, arg2);
    }




}
